import os
from pathlib import Path

"""
Django settings for loanshield_api project.

Generated by 'django-admin startproject' using Django 6.1.1

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

BASE_DIR = Path(__file__).resolve().parent.parent
